### ISSUE TITLE
npm WARN optional SKIPPING OPTIONAL DEPENDENCY

### ISSUE THREAD

**Issue by peng-howard** [lotabout/hexo-filter-fix-cjk-spacing#1]
您好，我在安装 fix-cjk 后遇到如下的问题，请问有解决的方法吗？

```
$ npm install hexo-filter-fix-cjk-spacing --save
hexo-site@0.0.0 D:\GitHub\stylus
-- hexo-filter-fix-cjk-spacing@0.0.3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

**Comment by lotabout** [comment]
@peng-howard 你好
1. `hexo-filter-fix-cjk-spacing` 本身不依赖任何其它的包，因此对 `fsevents` 的依赖应该是你装的其它包引入的。
2. 报的错是 `WARN` 应该不影响使用

麻烦你把 `node_modules` 删除，再重新执行 `npm install hexo-filter-fix-cjk-spacing --save` 试一试

**Comment by peng-howard** [comment]
感谢建议，因为之前的操作没有报过 fsevents 的依赖问题，所以我也不太确定哪出事了。现在的版本是生产版本，modules 多，等找台新机器再试试。

我目前的 npm 是 3.10.10，这个地址（https://github.com/npm/npm/issues/14042 ）的解决方法是降级到 3.10.7。

2017.4.16 升级 nmp 后，错误得到修正，感谢 @lotabout 的工作。
