### ISSUE TITLE
文章内完美解决，但如果添加了阅读更多，主页上的还是会显示多余空格

### ISSUE THREAD

**Issue by iXYYL** [lotabout/hexo-filter-fix-cjk-spacing#3]
主页上显示效果：
<img width="541" alt="屏幕快照 0001-06-08 18 27 00" src="https://user-images.githubusercontent.com/6551331/59145780-2457e180-8a1b-11e9-97fc-07a6f755ba8c.png">

进入博文后显示效果：
<img width="648" alt="屏幕快照 0001-06-08 18 27 12" src="https://user-images.githubusercontent.com/6551331/59145784-3174d080-8a1b-11e9-9033-3b1d1dfb399e.png">

实际代码：
<img width="186" alt="屏幕快照 0001-06-08 18 28 50" src="https://user-images.githubusercontent.com/6551331/59145796-4fdacc00-8a1b-11e9-85f3-1e36163792ee.png">

**Comment by lotabout** [comment]
@ikumo 使用新版 `0.0.4` 试试
