### ISSUE TITLE
未能实现预期功能

### ISSUE THREAD

**Issue by sghng** [lotabout/hexo-filter-fix-cjk-spacing#4]
多余的空格仍然存在。

Hexo 版本：7.2.0

NexT 版本：8.20.0

仓库地址：github.com/sghuang19/sghuang19.github.io/

**Comment by lotabout** [comment]
@sghuang19 请给一个具体示例。

我尝试用你的 blog 做渲染：

![image](https://github.com/lotabout/hexo-filter-fix-cjk-spacing/assets/1527040/b6b377d7-1a54-4320-8bb2-253cbcfc31a1)

![image](https://github.com/lotabout/hexo-filter-fix-cjk-spacing/assets/1527040/b20f1d32-a07c-4a43-9ba1-ea344d2b235e)

**Comment by sghng** [comment]
后来更换了 `hexo-renderer-markdown-it`，用 `markdown-it-cjk-breaks` 解决了空格的问题。再改回 `marked` 也不能复现问题了。
